[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc = "0.8.20"
evm_version = "london"
via_ir = true
optimizer = true
optimizer_runs = 20_000

fs_permissions = [{ access = "read-write", path = "./script/deployments"}]

[rpc_endpoints]
seth = "https://rpc-sepolia.rockx.com"
smnt = "https://rpc.sepolia.mantle.xyz"
eth = "https://rpc.ankr.com/eth"
mnt = "https://rpc.mantle.xyz"
bsc = "https://bsc-dataseed.binance.org"

[etherscan]
seth = { key = "${ETHERSCAN_TOKEN}", url="https://api-sepolia.etherscan.io/api?", chain="sepolia" }
smnt = { key = "${MANTLE_TOKEN}", url="https://explorer.sepolia.mantle.xyz/api?", chain=5003 }
eth = { key = "${ETHERSCAN_TOKEN}", url="https://api.etherscan.io/api?"}
mnt = { key = "${MANTLE_TOKEN}", url="https://explorer.mantle.xyz/api?"}
bsc = { key= "${BSCSCAN_TOKEN}", url="https://api.bscscan.com/api?", chain=56}

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
