[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc = "0.8.20"
evm_version = "london"
via_ir = true
optimizer = true
optimizer_runs = 20_000

fs_permissions = [{ access = "read-write", path = "./script/deployments"}]

[rpc_endpoints]
seth = "https://rpc-sepolia.rockx.com"
smnt = "https://rpc.sepolia.mantle.xyz"

[etherscan]
seth = { key = "${ETHERSCAN_API_KEY}", url="https://api-sepolia.etherscan.io/api?", chain="sepolia" }
smnt = { key = "${MANTLE_SEPOLIA_API_KEY}", url="https://explorer.sepolia.mantle.xyz/api?", chain=5003 }

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
